- name: Install Apache
  ansible.builtin.yum:
    name: httpd
    state: present

- name: Start and enable Apache
  ansible.builtin.systemd_service:
    name: httpd
    state: started
    enabled: true
